### ISSUE TITLE
Consolidated dokku app and plugin configuration

### ISSUE THREAD

**Issue by josegonzalez** [progrium/dokku#1558]
One thing we've been sorely lacking is a single way to refer and store configuration in the dokku world. 

- Application-related plugins usually store their data in the app's git directory in `/home/dokku`
- The official datastores store their data (and mount information) in `/var/lib/dokku/services/SERVICE/`
- Community plugins use stuff like `/home/dokku/.o_mysql`
- Dokku-wide config is usually stored in `/home/dokku`

Because of all the random ways in which data can be stored, there isn't exactly a simple way to save the state of an existing dokku installation. You can very easily push the container images to a registry and have backups occur from datastores, but actual config? Fffft.

Our `backup` plugin has been more or less ignored in the `0.3.x` line - totally my fault - and i think we need to start getting serious about this.

At one point, there was a note in a roadmap to store everything in a git directory. I think it's time we head down that road for 0.5.x.

---

### generic spec

- Data should be stored in a directory such as `/var/lib/dokku/config`.
  - `/var/lib/dokku/config/apps` - stores application data. Each application should get it's own directory, corresponding to the application name.
  - `/var/lib/dokku/config/plugins` - stores plugin data. Each plugin should get it's own directory, corresponding to the plugin name.
- We should provide a new `dokku-config` binary that is aware of the above paths and can interact with them.
  - Apps will interface with it using the `--app APP` flag, and can perform general crud actions against their own config.
  - Plugins will interface with it using the `--plugin PLUGIN` flag. Ditto on crud actions
  - The binary is a generic key-value store, and will be capable of triggering hooks on actions. For instance, we might want to log access, or ensure all actions get saved to an external datastore (git!).
- The backup system will be retrofitted to only work with the above system. If you want a backup, you basically get a tar of that directory. Users that want a backup of datastores should interface with those datastores either directly or through their plugin interfaces.
  - The official datastores all have ways of backing up/restoring data, so this is not a problem. We also cover all major datastores.

### open questions

- Do we handle encryption? I don't think it's worth it.
- How do we handle stuff like nginx? Does the nginx include path just change here?
- Should we serialize the data somehow, to json maybe?
- How do we ensure that data doesn't get accidentally overwritten by a shitty plugin/app/user?
- What language should it be written in? Golang is the obvious one to me, though handling plugins in it is annoying.

@Flink @michaelshobbs thoughts?

**Comment by josegonzalez** [comment]
#1571

**Comment by michaelshobbs** [comment]
Overall I'm in agreement. Some questions and comments
- Why do we need to provide a new binary for this function as opposed to making the config plugin as it is today more robust?
- I'm not clear on the difference in interaction regarding how a plugin would interface with config vs. an app.
- :+1: on config VCS
- Involving encryption include key management. I think this is best left up to the reader for now
- I think it's fine to move nginx config into this space as well
- Why serialize to anything? I think this makes the interaction more complex unless we build that into the aforementioned binary. Doing it in bash seems hairy and overtly complex. We need a solid use case for taking this on.
- I'm not sure it's up to us to save a user from a "shitty" plugin/app/user.
- Again, why create a new binary dependency?

**Comment by josegonzalez** [comment]
I guess moving it to a separate binary would allow us to iterate on that quicker than we would on the config plugin. As well, handling input/output in bash is kind of annoying, and it would be nice to be able to use a higher-level language to handle this (not to mention it could also decrease the amount of logging output if we write it correctly).

**Comment by Flink** [comment]
Interesting ideas as I think also that we need some sort of central repository for managing config. Indeed it needs to be versioned somehow with git for example. We need to have a way to bind a revision of an application config with a tagged image to be able to do rollbacks and things like that (like Heroku) :)
Another thing I saw the other day while playing with their addons is that when an addon declares a config var on your app, you can’t manage it directly. Only the addon can manage it so this is an interesting lead to explore to avoid unwanted rewrites and thing like that.
Separate “config stores” for nginx and plugins seems a good idea. As for the serialization, if we really want that, maybe we can use toml?
For a new binary, I don’t know if it’s necessary nor if Go is a good choice ;) (I find it way too verbose among other things)

Otherwise :+1: :)

**Comment by u2mejc** [comment]
@josegonzalez so looking this over, I have a few questions:
- Do you have a copy of the source for the "binary"? I assume this is just because strings are hard to handle in bash?
- You are proposing to move all app data out of ~/dokku/<app>, to /var/lib/dokku/config/apps/<app> correct?
- For data not committed in git; any changes to quasi-ephemeral data like environmental vars (ENV_FILE)?

Moving the location of the apps is simply handful of greps, is there an advantage to a new location or is it just to force adoption for thirdparty plugin authors? In the same line of light, excluding all backup abilities (manual or automated), what other advantages are gained by the dokku community with these changes? One less part written in bash is a good answer too. :wink:

**Comment by josegonzalez** [comment]
- I haven't written any code for said binary.
- Not the git directories, just any config files. For instance, we'd no longer be copying `nginx.conf.template` or whatever into `/home/dokku/DERP/`, and instead to the `/var/lib/dokku/config/apps/DERP/` directory.
- Any files that dokku creates that are config would somehow go in this new config dir.

The advantage is separating all our config from the bare git directory, which allows us to both simplify backup/copies of applications, but also removes any doubt about what files go where. In the past we just never gave anyone any direction on where to put stuff, so shit has gone everywhere.

**Comment by josegonzalez** [comment]
I started giving this a good, hard look. I believe once the `config` changes from #2751 land, we can look into this. I'd be down for something like an `attributes` or `properties` plugin. It could be a minimalist wrapper around something like [bash-filedb](https://github.com/josegonzalez/bash-filedb), while allowing users to swap in/out the underlying binary that is called (in case they want to use something else, like redis or vault).

I'm not sure how data migration would work - maybe some sort of read-through layer that allowed us to fallback to a `config` key? - but thats something to think about. I definitely want to make sure we move all config out of the application repositories though.

**Comment by mcohen9** [comment]
Whats the status on this? Looking for a way to backup and restore my dokku apps,plugins and configurations.

**Comment by josegonzalez** [comment]
@mcohen9 Hi! Any "status" would likely be posted on this issue - either in the form of a comment, linked pr, or issue closure.

As this is an open source project, any change in "status" to an issue will have to be contributed by our users - this includes you! - or project maintainers at their leisure. If you'd like to sponsor the work on this, it's probably ~20 hours of my time to move everything over to the new system, so feel free to email me if thats something you want to consider.

As always, pull requests welcome!

**Comment by josegonzalez** [comment]
Open question: Where should application repositories be stored? `/var/lib/dokku/data/git` might be reasonable. One thing moving the repositories breaks is how applications are listed/verified as existing, so we'd want to track that separately as well.

**Comment by t0xicCode** [comment]
@josegonzalez anything I could do to help?

**Comment by josegonzalez** [comment]
Biggest thing would be to see what files are being read from the `DOKKU_ROOT` dir that aren't git-related and move them to the appropriate place in `/var/lib/dokku`. I haven't gone through and documented these just yet, so that would be a good first step.

**Comment by t0xicCode** [comment]
I found 3 files in `DOKKU_ROOT` that are being read in my case (with virtualhosts enabled):
* `VERSION`
* `ENV`
* `VHOST`

I don't see why there is both a `STABLE_VERSION` in `/var/lib/dokku` and a `VERSION` in `DOKKU_ROOT`, especially if the `STABLE_VERSION` file is copied onto the `VERSION` file as part of the installation process. IMO, the version information should be baked into the binary at compile/build time, and not be a property of the environment. If we want to maintain it as a file, why not a single `version` file in `/var/lib/dokku`?

For `ENV`, it should be fairly simple to move for now, and should only require modifications to the _config_ plugin. Next step would be to convert config from the single file to the _Property_ system.

For `VHOST` and `HOSTNAME`, moving it is feasible, but it'll be a bit more involved, as these files are accessed from a few various places (plugins, web-installer, package installation, and more). Once again, I think this would be well served by leveraging the _Property_ system.

Should I start on a PR to migrate these files to `/var/lib/dokku`?

**Comment by t0xicCode** [comment]
Awesome! I'll get on that. I haven't looked at the files within the directories yet, but that's next on my steps.

**Comment by hugopeixoto** [comment]
As for the `VHOST` vs `HOSTNAME` distinction, I found this issue https://github.com/dokku/dokku/pull/2196, which has a comment stating:

> If I understand the original intent, `HOSTNAME` is for the host itself and `VHOST` is for the default domain for all apps. Then of course there's `VHOST` in the app directory.
>
> My 2 cents: I think we should leave it as is and make the docs more clear.

Hostname doesn't seem to be used in many places. I'll spend some time investigating what the differences are and report my conclusions.

**Comment by hugopeixoto** [comment]
This comment ended up being quite long. Let me know if you want me to move this somewhere else,.

The following concepts are used in the codebase: `domain`, `url`, `vhost`, and `hostname`. I think that `domain` and `vhost` are interchangeable.

When you install `dokku`, `VHOST` gets copied from `HOSTNAME` via the `00_dokku-standard/install` hook.

If you use the web installer, this file will be removed if you don't select the "use vhosts" checkbox.

The `domains-list` trigger makes the `domains` plugin print, **if vhosts are enabled for this app**, the contents of the first of these three files to exist:
- `$DOKKU_ROOT/$APP/VHOST`
- `$DOKKU_ROOT/VHOST`
- `$DOKKU_ROOT/HOSTNAME`

We detect if vhosts are enabled for an app or not via the config `NO_VHOST`. Running `dokku domains:disable $APP` sets `NO_VHOST=1`, while `dokku domains:enable $APP` sets it to `1`. Enabling/disabling domains also creates/removes the `$DOKKU_ROOT/$APP/VHOST`.

Enabling vhosts on an app will create the `$DOKKU_ROOT/$APP/VHOST` file with the contents from `$DOKKU_ROOT/VHOST` prepended by `$APP`. If there's no global vhost file (`dokku domains:remove-global`), it will create an empty file. It will not use the contents of `$DOKKU_ROOT/HOSTNAME`.

`dokku domains:report` prints the contents of `$DOKKU_ROOT/$APP/VHOST` (app) and `$DOKKU_ROOT/VHOST` (global).

Running the following commands leaves things in a state that I didn't expect:

```shell
dokku domains:disable $APP
dokku domains:remove-global example.com
dokku domains:enable $APP
dokku domains:add-global example.com
```

This will end up with `$DOKKU_ROOT/$APP/VHOST` being empty, while I'd expect it to be `$APP.example.com`. I needed to disable/enable domains on `$APP` to get it to have the expected contents. This might be happening because we can set custom vhosts even with the global vhost disabled. I'm not sure.

Without a global vhost (`dokku domains:remove-global example.com`), I can add a vhost for that app only with `dokku domains:add $APP someotherdomain.com`.

`plugins/nginx-vhosts/functions` handles `nginx_build_config`, which creates nginx.conf, either with vhosts or port based.
It uses the `domains-list` trigger to fetch the value to put `server_name $here`.

Given all of this, the `domains-list` behavior listed above, printing the first of:

- `$DOKKU_ROOT/$APP/VHOST`
- `$DOKKU_ROOT/VHOST`
- `$DOKKU_ROOT/HOSTNAME`

makes some sense, but not completely. If vhosts are enabled for the app, nginx will be configured with `$DOKKU_ROOT/$APP/VHOST`. However, if vhosts are not enabled for this app (meaning we should use port based routing), nginx might end up with `$DOKKU_ROOT/VHOST` instead of `$DOKKU_ROOT/HOSTNAME`, which feels like a potential issue.

`plugins/nginx-vhost/functions#nginx_build_config` decides which server names to use in HTTP and HTTPS scenarios separately. The `NONSSL_SERVER_NAMES` variable uses the results of the `domains-list` trigger. The `SSL_SERVER_NAMES` are a bit more complex. It starts by extracting the `ssl_hostnames` from the domain names listed in the certificate (using `openssl`), using a function provided by the `certs` plugin. If vhosts are enabled, it filters `$DOKKU_ROOT/$APP/VHOST` to those in the `ssl_hostnames` list and stores them in `SSL_VHOSTS`. If vhosts are disabled, it stores `$DOKKU_ROOT/HOSTNAME`. `SSL_SERVER_NAMES` is then constructed by taking `SSL_VHOSTS` and filtering out any server names already in `NONSSL_SERVER_NAMES` (because the `server{}` block with `listen ssl` uses both SSL and NONSSL server names, and the `server{}` block with nonssl listen only handles exclusively HTTP server names).

Port management is done by `configure_nginx_ports`, which stores the results by calling `config_set --no-restart $APP DOKKU_PROXY_PORT_MAP=<portmapping>`

This behavior matches my understanding of using `$APP/VHOST` when the app has vhosts enabled and `HOSTNAME` when it doesn't.

At the end of the function, **if vhosts are enabled for this app**, the `$DOKKU_ROOT/$APP/URLS` file is written with `SSL_VHOSTS` and `NONSSL_VHOSTS`, all of them prefixed with `https://` (even the NONSSL ones), unless there's no SSL for this app, in which case, they're all prefixed with `http://`. Urls in this file **do not contain neither upstream nor proxy (listen) ports**. This is expected, since vhosts are enabled.

The other use of `$DOKKU_ROOT/VHOST` and `$DOKKU_ROOT/HOSTNAME` is in `plugins/common/functions#internal_get_app_urls`. This function has two main branches.

If the `$DOKKU_ROOT/$APP/URLS` file exists (meaning vhosts are enabled), it prints its content. It also prints urls built by combining `DOKKU_PROXY_PORT_MAP` with `domains-list`. I'm guessing that this is to allow apps to have both vhost based and port based routing.

If the `$DOKKU_ROOT/$APP/URLS` file does not exist (meaning vhosts are disabled):
- if proxy is disabled for this app (config `DOKKU_DISABLE_PROXY`), it prints `$DOKKU_ROOT/HOSTNAME` with the container port
- if there's a proxy map, it builds urls based on `$DOKKU_ROOT/HOSTNAME` and listen port
- if there it uses RAW_TCP_PORTS, it builds an `http` url with `$DOKKU_ROOT/HOSTNAME` and the raw tcp port
- if none of the above apply, it prints an url based on `$DOKKU_ROOT/VHOST`, without port.

This last scenario, which feels like a fallback, feels off. Why would it use `$DOKKU_ROOT/VHOST` and not `$DOKKU_ROOT/HOSTNAME`? It's not even using `$DOKKU_ROOT/$APP/VHOST`.

This `internal_get_app_urls` is (indirectly) used by `dokku url`, `dokku urls`, and when it's printed after deploy for user convenience.

## Conclusions

`$DOKKU_ROOT/HOSTNAME` is used when vhosts for a given app are disabled. It's the hostname of the server. It's used in nginx configs and in commands that print the urls for an app.

`$DOKKU_ROOT/$APP/VHOST` is used when vhosts are enabled. Again, used in nginx configs and in commands that print the urls for an app.

`$DOKKU_ROOT/VHOST` **should** only be used when building `$DOKKU_ROOT/$APP/VHOST`, as a prefix. We're currently using it as a fallback in two places that feel wrong: `get_app_domains` and `internal_get_app_urls`.

We can end up in scenarios with `NO_VHOST=0` with `$DOKKU_ROOT/$APP/VHOST` empty. This inconsistency might be a problem.

Unrelated: When naming variables, we use `_FILE` and `_PATH` interchangeably, sometimes when referring to the same file. This might be worth fixing to help with grepping.

I don't completely understand the behavior of the `$DOKKU_ROOT/$APP/URLS`. I don't know why it only contains `https://` urls, and it ignores `PROXY_SSL_PORT`.

**Comment by josegonzalez** [comment]
Whats left?

- [ ] The URLS files. Those should be moved... somewhere. Not sure where. Same with VHOST files.
- [ ] The ENV file. This might be able to be moved to the property system, not sure yet.
- [ ] Docker options. Prime candidate for moving to the property system. Hopefully not too much is parsing these files directly.
- [x] DOKKU_SCALE. We have an issue to refactor this (#3703), so not necessary to count here.
- [x] `src.tar`. #3458 should remove the need for this.
- [x] `nginx.conf`. Tracked in #3443. We should also handle `tls` certificates too.
- [x] Deploy lock files. Can we move these to /var/lock or something? https://github.com/dokku/dokku/pull/6156
- [x] `cache` dir. Closed by #3454
- [ ] IP/PORT/CONTAINER files. Might be handled by #3703 but not quite sure yet.

**Comment by josegonzalez** [comment]
Update:

- `IP`/`PORT` files can probably be computed on the fly and removed.
- `ENV` file should move to `/var/lib/dokku/config/config/ENV`
- `DOCKER_OPTIONS_*` can move to `/var/lib/dokku/config/docker-options/phase-*`, where `*` is the name of the phase. This will also allow us to support process-specific options at some point.
- `nginx.conf` files should move to `/etc/nginx/dokku.d` (and tls somewhere appropriate). There is a ticket open for that.

I'm going to try and move the ENV/docker options files and refactor the ip/port stuff in the next PR, after which we can close this issue as everything else is tracked separately.
