### ISSUE TITLE
Roadmap for 0.4.0 Release

### ISSUE THREAD

**Issue by progrium** [progrium/dokku#56]
High level goals are refactoring, documentation, and testing. New features include addons and more pre-made images.

In no particular order:
- [x] Extensive first pass at documentation
- [x] More extensive testing (tests commands, etc)
- [ ] Integration of slugbuilder/slugrunner
- [ ] Move buildpack integration testing to slugbuilder/slugrunner
- [ ] Heroku-style addon interface
- [ ] Potentially packaged as a Docker image itself
- [ ] Ready to go disk images on multiple cloud platforms
- [ ] Cleanup the app organization and stop messing around in the git bare repo
- [ ] Store applications' config in a git repo

**Comment by dmr** [comment]
Since the last update here 12 releases in 0.3.0 were made, that is a lot of releases!
What is the status of 0.4.0?

**Comment by progrium** [comment]
@josegonzalez has been on a path of integrating PRs and fixing issues, and more recently setting up a Debian package ... I've been working on refactoring a lot of the dependent components and when I get back to Dokku it will probably involve a huge refactoring that touches on all of these items and more... I don't know the logistics of whether we'll maintain two branches for very long or at what point my branch is acceptable for master, but I'd like it to then move towards a 1.0 RC.

So I don't know, it depends on @josegonzalez whether he's going to go into 0.4.0 with his path, but like I said my branch will eventually capture most of the items here. Not sure if we should keep this or call it something else...

**Comment by josegonzalez** [comment]
I think the two things that will probably be done on this list for 0.4.0 are:

- packaging in some sense (deb packages most likely)
- heroku-style addons

There are a few others, but we've been pretty good about making small, quick releases. I don't personally like the idea of making a roadmap for releases - you get what you get! - so tbh I'll just close this. We'll build features as the community finds them useful or necessary, not to fit a timeline.

@progrium TBH we should probably do such a major refactor sooner rather than later. If you've got ideas, I'd love to hear them. Better that we make any changes now before we continue building out the official plugin structure etc :) It would also be good to gradually introduce such changes - for instance, nginx support has evolved nicely since the 0.3.0 to the current 0.3.12 release - so maybe we'll make the 0.4.0 line the one where we refactor all the things?

I don't know when we'll hit a 0.4.0 - depends on us completing the two tasks I mentioned above, as well as docs and platform stability - but rest assured, it'll be a very solid release.

If you'd like to have input on features, please feel more than free to drop by the irc channel or comment on existing issues/pull requests. That's basically how I prioritize things.

**Comment by dmr** [comment]
Thanks for the quick replies. Are you guys using dokku in production?

**Comment by motin** [comment]
@dmr If that is a general question, then yes, we use it in production through https://github.com/neam/dokku-host-provisioning

**Comment by josegonzalez** [comment]
@motin you should upgrade your base installation, a few of those extra features are now in dokku core ;)

**Comment by dmr** [comment]
@motin Thanks for that hint, I'll look into it!

**Comment by motin** [comment]
@josegonzalez Yes, of course, but first things first - the current base installation is what we use in production and thus has been tested and proven to work well enough. It is being released as dokku-host-provisioning 1.0.0 while an upgrade is prepared in the develop-branch. :)
